### ISSUE TITLE
 This is not an issue but a question on how to build maui repo, run control samples and step thru maui repo code.

### ISSUE THREAD

**Issue by davefxy** [LanceMcCarthy/DevOpsExamples#93]
I have tried following the repo development guide but cant seem to get it to compile successfully. I am asking the question here because you seem like you might have an idea if this is possible and how.

**Comment by LanceMcCarthy** [comment]
I'm guessing you mean in Visual Studio and not in CI-CD workflow? This repo is specifically to show how to use Telerik controls in a CI-CD build server.

In any case, I can give you a head start, but for further assistance with the general .NET and Visual Studio stuff, you can get help here (see the README first) => https://github.com/dotnet/maui

In short, you need to have the MAUI workload installed in order for Visual Studio to even be able to know what to do with a MAUI project. Here's the exact steps you can take to get started:

1. https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?tabs=vswin 
2. https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?tabs=vswin&pivots=devices-windows 

At that point, you can now try someone else's code. continue to step #3 in the .NET MAUI readme https://github.com/dotnet/maui

Finally, you can follow the tutorials and courses here => https://learn.microsoft.com/en-us/dotnet/maui/get-started/resources
